initial_pose: [-0.3, 0.0, 0.0, 0.6, -0.3, 0.0,
               -0.3, 0.0, 0.0, 0.6, -0.3, 0.0,
               0.0, 
               0.0, 0.0, 0.0, 0.0, 0.0,
               0.0, 0.0, 0.0, 0.0, 0.0,
               0.2]

initial_kp:   [150,150,150,150,50,50,
               150,150,150,150,50,50,
               200,
               0,0,0,0,0,
               0,0,0,0,0,
               50]

initial_kd:   [2,2,2,2,1.5,1,
               2,2,2,2,1.5,1,
               3,
               0,0,0,0,0,
               0,0,0,0,0,
               1]
